exp_name: base_whisper1280_code48_test

whisper_dim: 1280
codebook_size: 48
hidden_dim: 512
code_dim: 256

train_filelist: data/test_wrongpath/train.txt
val_filelist: data/test_wrongpath/val.txt
log_dir: logs
val_interval: 1 # Epoch

lr: 1e-4
c_vqloss: 1
c_reconloss: 0.5
batch_size: 2

keep_ckpts: 2
