exp_name: rainbow_studio_frozen
train:
  lr: 1e-5
  lr_stage2: 1e-5
  batch_size: 12
  filelist: data/Rainbow/train.txt
  val_filelist: data/Rainbow/val.txt
  epochs: 500
  lam_mel: 40
  lam_kl: 1.0
  freeze_prior: True
model:
  spec_channels: 1025
  segment_size: 32
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
  n_heads: 2
  n_layers: 6
  kernel_size: 3
  p_dropout: 0
  resblock: '1'
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  upsample_rates: [12, 10, 2, 2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [24, 20, 4, 4]
  spk_embed_dim: 110
  gin_channels: 256
  sr: 48000
data:
  hop_length: 480
  segment_size: 17280
  max_len: 480000
  n_fft: 2048
  num_mels: 128
  sampling_rate: 48000
  win_size: 2048
  fmin: 0
  fmax: null
  num_workers: 4